//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.22 at 06:52:45 PM CET 
//


package com.anzepintar.ozrpp.tmxconvert;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tu"
})
@XmlRootElement(name = "body")
public class Body {

    protected List<Tu> tu;

    /**
     * Gets the value of the tu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tu }
     * 
     * 
     */
    public List<Tu> getTu() {
        if (tu == null) {
            tu = new ArrayList<Tu>();
        }
        return this.tu;
    }

}
