//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 06:31:19 PM CEST 
//


package com.anzepintar.ozrpp.converters.xliffconvert;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attrType_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="attrType_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fmt"/>
 *     &lt;enumeration value="ui"/>
 *     &lt;enumeration value="quote"/>
 *     &lt;enumeration value="link"/>
 *     &lt;enumeration value="image"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "attrType_type")
@XmlEnum
public enum AttrTypeType {

    @XmlEnumValue("fmt")
    FMT("fmt"),
    @XmlEnumValue("ui")
    UI("ui"),
    @XmlEnumValue("quote")
    QUOTE("quote"),
    @XmlEnumValue("link")
    LINK("link"),
    @XmlEnumValue("image")
    IMAGE("image"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AttrTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttrTypeType fromValue(String v) {
        for (AttrTypeType c: AttrTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
