//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 06:31:19 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:xliff:document:2.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.anzepintar.ozrpp.converters.xliffconvert;
