//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 06:31:19 PM CEST 
//


package com.anzepintar.ozrpp.converters.xliffconvert;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeForMrkValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeForMrkValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="generic"/>
 *     &lt;enumeration value="comment"/>
 *     &lt;enumeration value="term"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "typeForMrkValues")
@XmlEnum
public enum TypeForMrkValues {

    @XmlEnumValue("generic")
    GENERIC("generic"),
    @XmlEnumValue("comment")
    COMMENT("comment"),
    @XmlEnumValue("term")
    TERM("term");
    private final String value;

    TypeForMrkValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeForMrkValues fromValue(String v) {
        for (TypeForMrkValues c: TypeForMrkValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
